<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<groupId>frostillicus.nsf</groupId>
	<artifactId>nsf-maven-repository</artifactId>
	<packaging>domino-nsf</packaging>
	<version>0.2.0-SNAPSHOT</version>
	
	<repositories>
		<repository>
			<id>openntf</id>
			<url>https://artifactory.openntf.org/openntf</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.11.0</version>
				<executions>
					<execution>
						<id>prepare-xpages-jee</id>
						<goals>
							<goal>unpack</goal>
						</goals>
						<phase>generate-sources</phase>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>org.openntf.xsp</groupId>
									<artifactId>org.openntf.xsp.jakartaee.updatesite</artifactId>
									<version>3.6.0</version>
									<type>zip</type>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
				<groupId>org.openntf.maven</groupId>
				<artifactId>nsfodp-maven-plugin</artifactId>
				<version>4.1.0</version>
				<extensions>true</extensions>
				<configuration>
					<updateSites>
						<updateSite>${project.build.directory}/dependency</updateSite>
					</updateSites>
					<templateName>MavenRepository</templateName>
					<compilerLevel>17</compilerLevel>
					<acl>
						<entries>
							<entry>
								<name>-Default-</name>
								<defaultEntry>true</defaultEntry>
								<level>manager</level>
								<deleteDocs>true</deleteDocs>
							</entry>
							<entry>
								<name>[-Default-]</name>
								<level>noaccess</level>
							</entry>
							<entry>
								<name>[OtherDomainServers]</name>
								<level>noaccess</level>
							</entry>
							<entry>
								<name>[LocalDomainAdmins]</name>
								<level>manager</level>
								<deleteDocs>true</deleteDocs>
								<noReplicate>false</noReplicate>
							</entry>
							<entry>
								<name>[LocalDomainServers]</name>
								<level>manager</level>
								<deleteDocs>true</deleteDocs>
								<noReplicate>false</noReplicate>
							</entry>
							<entry>
								<name>LocalDomainAdmins</name>
								<level>manager</level>
								<deleteDocs>true</deleteDocs>
								<noReplicate>false</noReplicate>
							</entry>
						</entries>
					</acl>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<descriptors>
						<descriptor>assembly.xml</descriptor>
					</descriptors>
					<finalName>NSF-Maven-Repository-${project.version}</finalName>
					<appendAssemblyId>false</appendAssemblyId>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
